// <auto-generated />
namespace Server_WCF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202210261322216_Init-Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
